#!/bin/bash
set -e

echo "[agentsmith] start.sh v3 (2026-02-08 19:45)"

CONFIG_PATH="/data/.openclaw/openclaw.json"
SOUL_PATH="/data/workspace/SOUL.md"
ENV_PATH="/data/.openclaw/.env"

# Ensure subdirectories exist — Railway volume mount wipes build-time dirs
mkdir -p /data/workspace /data/.openclaw

# resolve_config: expand ${VAR:-default} patterns and coerce JSON types.
# OpenClaw >=2026.1.30 no longer interpolates env vars in config JSON.
resolve_config() {
  node -e '
    const raw = require("fs").readFileSync(0, "utf8");
    const resolved = raw.replace(/\$\{([^}]+)\}/g, (_, expr) => {
      const [name, fallback] = expr.split(":-");
      return process.env[name] || fallback || "";
    });
    const cfg = JSON.parse(resolved);
    if (typeof cfg.gateway?.port === "string") {
      cfg.gateway.port = parseInt(cfg.gateway.port) || 3000;
    }
    const tg = cfg.channels?.telegram;
    if (tg) {
      if (typeof tg.enabled === "string") tg.enabled = tg.enabled === "true";
      if (tg.botToken === "") delete tg.botToken;
    }
    process.stdout.write(JSON.stringify(cfg, null, 2));
  '
}

# Write openclaw config from env var (pushed by Agent Smith on provision/sync)
# Falls back to the default baked into the image
if [ -n "$OPENCLAW_CONFIG_JSON" ]; then
  echo "$OPENCLAW_CONFIG_JSON" | resolve_config > "$CONFIG_PATH"
  echo "[agentsmith] openclaw.json written from env"
else
  if [ ! -f "$CONFIG_PATH" ]; then
    resolve_config < /app/openclaw.json.default > "$CONFIG_PATH"
    echo "[agentsmith] openclaw.json initialized from default"
  fi
fi

# Decode brand data from env var (base64-encoded SOUL.md pushed by brand sync)
if [ -n "$SOUL_MD" ]; then
  echo "$SOUL_MD" | base64 -d > "$SOUL_PATH"
  echo "[agentsmith] SOUL.md written ($(wc -c < "$SOUL_PATH") bytes)"
else
  if [ ! -f "$SOUL_PATH" ]; then
    cp /app/workspace/SOUL.md.default "$SOUL_PATH"
    echo "[agentsmith] SOUL.md initialized from default"
  fi
fi

# Write .env file for OpenClaw to pick up API keys.
# OpenClaw reads $OPENCLAW_STATE_DIR/.env for provider credentials.
# Railway injects these as process env vars; we persist them so OpenClaw's
# daemon and agent subsystems can find them reliably.
{
  echo "# Auto-generated by start.sh — do not edit"
  [ -n "$ANTHROPIC_API_KEY" ]   && echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY"
  [ -n "$OPENAI_API_KEY" ]      && echo "OPENAI_API_KEY=$OPENAI_API_KEY"
  [ -n "$GEMINI_API_KEY" ]      && echo "GEMINI_API_KEY=$GEMINI_API_KEY"
  [ -n "$OPENROUTER_API_KEY" ]  && echo "OPENROUTER_API_KEY=$OPENROUTER_API_KEY"
  [ -n "$GROQ_API_KEY" ]        && echo "GROQ_API_KEY=$GROQ_API_KEY"
  [ -n "$XAI_API_KEY" ]         && echo "XAI_API_KEY=$XAI_API_KEY"
  [ -n "$MISTRAL_API_KEY" ]     && echo "MISTRAL_API_KEY=$MISTRAL_API_KEY"
} > "$ENV_PATH"
echo "[agentsmith] .env written with $(grep -c '=' "$ENV_PATH" || echo 0) key(s)"

# SOCKS5 residential proxy for WhatsApp — routes all outgoing TCP through
# a residential IP so WhatsApp doesn't reject the datacenter IP.
# Set SOCKS5_PROXY_URL=socks5://user:pass@host:port in Railway env vars.
echo "[agentsmith] entering proxy section, SOCKS5_PROXY_URL=${SOCKS5_PROXY_URL:+SET}"
if [ -n "$SOCKS5_PROXY_URL" ]; then
  # Parse SOCKS5 URL with pure bash — no node -e file-writing needed
  PROXY_BODY="${SOCKS5_PROXY_URL#*://}"
  PROXY_CREDS="${PROXY_BODY%%@*}"
  PROXY_HOSTPORT="${PROXY_BODY#*@}"
  PROXY_HOST="${PROXY_HOSTPORT%%:*}"
  PROXY_PORT="${PROXY_HOSTPORT##*:}"
  PROXY_USER="${PROXY_CREDS%%:*}"
  PROXY_PASS="${PROXY_CREDS#*:}"

  # proxychains4 requires an IP address for the first proxy in the chain
  PROXY_IP=$(getent hosts "$PROXY_HOST" | awk '{print $1; exit}')
  if [ -z "$PROXY_IP" ]; then
    echo "[agentsmith] ERROR: could not resolve $PROXY_HOST to IP" >&2
    PROXY_IP="$PROXY_HOST"
  fi

  cat > /etc/proxychains4.conf <<PROXYEOF
strict_chain
quiet_mode
tcp_read_time_out 15000
tcp_connect_time_out 10000

[ProxyList]
socks5 $PROXY_IP $PROXY_PORT $PROXY_USER $PROXY_PASS
PROXYEOF

  echo "[agentsmith] SOCKS5 proxy configured: ${PROXY_IP}:${PROXY_PORT} (${PROXY_HOST})"

  # Quick connectivity test — verify the proxy actually works before starting
  echo "[agentsmith] Testing proxy connectivity..."
  if proxychains4 curl -sf --max-time 10 -o /dev/null -w "%{http_code}" https://web.whatsapp.com 2>&1; then
    echo "[agentsmith] Proxy verified, starting with proxychains"
    GATEWAY_CMD="proxychains4 openclaw gateway"
  else
    echo "[agentsmith] WARNING: Proxy test failed, starting WITHOUT proxy"
    GATEWAY_CMD="openclaw gateway"
  fi
else
  echo "[agentsmith] No SOCKS5 proxy (SOCKS5_PROXY_URL not set)"
  GATEWAY_CMD="openclaw gateway"
fi

echo "[agentsmith] Starting OpenClaw gateway (version: ${OPENCLAW_VERSION:-unknown})"

exec $GATEWAY_CMD
